const express = require('express')
const router = express.Router()
const clientController = require('../controllers/clientController')
const cartController = require('../controllers/cartController')
const orderController = require('../controllers/orderController')
const authMiddleware = require('../middlewares/Authmiddleware')
const couponController = require('../controllers/couponController')
const walletController = require('../controllers/walletController')

router.get('/' ,clientController.home)
router.get('/login', clientController.login)
router.post('/login',clientController.loginpost)
router.get('/logout',clientController.logout)
router.get('/signup',clientController.signup)
router.post('/signup',clientController.signuppost)
router.get('/otp', clientController.otp);
router.post('/otp',clientController.otppost)
router.get('/forgotpassword',clientController.forgotpassword)
router.post('/forgotpassword',clientController.forgotpasswordpost)
router.get('/product_shirts',clientController.product_shirts)
router.get('/productpage',clientController.productpage)
router.get('/cart',cartController.cart) 
router.get('/cartpost/:productId',cartController.addToCart)
router.get('/cartadd/:productId',cartController.addToCart) 
router.get('/cartremove/:productId',cartController.removefromcart) 
router.post('/deletecart/:productId',cartController.deleteFromCart)
router.get('/userprofile', authMiddleware,clientController.userprofile) 
router.get('/addaddress', authMiddleware,clientController.addaddress)
router.post('/addaddress', authMiddleware,clientController.addaddresspost)
router.get('/edituser/:userId', authMiddleware,clientController.edituser)
router.post('/edituser/:userId', authMiddleware,clientController.editpost)
router.get('/checkout', authMiddleware,cartController.checkout)
router.post('/payment/:amount', authMiddleware,cartController.payment)
router.post('/addresssave', authMiddleware,clientController.saveaddress)
router.get('/confirmpage', authMiddleware,orderController.confirmpage)
router.get('/orders', authMiddleware,orderController.orders)
router.get('/orderhistory', authMiddleware,orderController.orderhistory)
router.get('/orderdetail', authMiddleware,orderController.orderdetail) 
router.post('/updateAddress', authMiddleware,clientController.updateAddress)
router.get('/editaddress/:addressId', authMiddleware,clientController.editaddress)
router.post('/editaddress/:addressId', authMiddleware,clientController.editaddresspost)
router.get('/products',clientController.productsort)
router.get('/productsearch',clientController.productsearch)
router.post('/applycoupon',couponController.applycoupon)
router.get('/wallet',walletController.wallet)
router.get('/walletadd/:totalAmount/:orderid', walletController.walletadd);


module.exports = router 